language: go

sudo: false

matrix:
  include:
    - go: 1.x
      env: LATEST=true

before_install:
  - go get github.com/mitchellh/gox

script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go vet $(go list ./... | grep -v /vendor/)
  - if [ "${LATEST}" = "true" ]; then gox -os="linux darwin windows" -arch="amd64" -output="sendshit-{{.OS}}-{{.Arch}}" -ldflags "-X main.Rev=`git rev-parse --short HEAD`" -verbose ./...; fi

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OxgEM+VZkK90LRLyd5HM4dqKrOBVVEcd9X3ew65QX5uGrg55Q9fFbZVxYMzS6+huYGYXVBR9iViJHw+GmR3yGfZO+rjsybqBfSF4QM95zEmxDycNpqjrtpQbwLt5VXUc3Rm/BWHCdqmbZ5FdePHTvbOpGfBSmLOimZpsergvk4E48A2XUo09yTtqwTf8RRaOuQgrgv2tCUlJS7ICO+hdN6ssfeqPPvm/hkOAyWM+zY0aBMKRXZ1hSVoQ2wcf0KuoRAT4aYWGpYfjfPbZWQqTKeRGWx9e0vbyxKhDvhXvE36hW8AQnxPYrRPY1rHF61+8jLPaTkfIqM2gtnXn8KgXFqLxLfXPwZGL5BF3d7cYlZ3mu1KmI0s027IhCWC+YuEeR+yATk5Ahfp6xrMzNDsjCr8gn4SEH6RAJLu9QYHpjgy2SRrxqUVu4h6scFWvLAJMLQYdm90fyMvn5EpeL0nnD/OVcfdDKtHTxN3jQqD8SV5CPw26RnIacGUbdXy8K6koTsHmHGJScmpjggmanuBg0xVp4FeAwBwHN5X7C0hSdKMKuhy2MhqwZafqy5mLua2KQk0Ud2IT+yxfez6k6JnOKI+XJClDh1qsE9WnMIy9NuPC3oKIMqnbrq+Ht4vqVL2ox88H5fZ0//fxlHYQPm9ai97jeL84kF/TiUkq9ZMqC/8=
  file:
    - sendshit-windows-amd64.exe
    - sendshit-darwin-amd64
    - sendshit-linux-amd64
  on:
    repo: shitty-inc/sendshit-cli
    condition: $LATEST = true
    tags: true
